name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: Linux-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            Linux-npm-

      - name: Initialize npm project (if missing)
        run: |
          if [ ! -f package.json ]; then
            echo "Creating package.json"
            npm init -y
          fi

      - name: Install a default dependency (if needed)
        run: |
          if [ ! -f package-lock.json ]; then
            echo "Installing axios (example)"
            npm install axios
          fi

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            echo "Using npm ci"
            npm ci
          else
            echo "Using npm install"
            npm install
          fi

      - name: List generated files
        run: ls -l

      - name: Run app or scripts
        run: echo "Ready to build or test your app"
